SELECT A.FLAVOR
FROM (SELECT F.FLAVOR, (SUM(F.TOTAL_ORDER) + SUM(J.TOTAL_ORDER)) AS TOTAL
      FROM FIRST_HALF F, JULY J
      WHERE F.FLAVOR = J.FLAVOR
      GROUP BY F.FLAVOR
      ORDER BY TOTAL DESC) A
LIMIT 3;