SELECT D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME
FROM DEVELOPERS D,
    (SELECT SUM(CODE) AS SUM_CODE
     FROM SKILLCODES
     WHERE CATEGORY = 'Front End') S
WHERE S.SUM_CODE & D.SKILL_CODE
ORDER BY D.ID ASC;