SELECT I.NAME, I.DATETIME
FROM ANIMAL_INS I, ANIMAL_OUTS O
WHERE I.ANIMAL_ID NOT IN (SELECT I.ANIMAL_ID FROM ANIMAL_INS I, ANIMAL_OUTS O WHERE I.ANIMAL_ID = O.ANIMAL_ID)
GROUP BY I.ANIMAL_ID
ORDER BY I.DATETIME
LIMIT 3;