SELECT PLACES.ID, PLACES.NAME, PLACES.HOST_ID
FROM PLACES, (SELECT ID, NAME, HOST_ID
              FROM PLACES 
              GROUP BY HOST_ID 
              HAVING COUNT(ID) >= 2) AS NEW_PLACES
WHERE PLACES.HOST_ID = NEW_PLACES.HOST_ID