SELECT DISTINCT H.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR AS C, 
     (SELECT CAR_ID
      FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
      WHERE START_DATE BETWEEN '2022-10-01' AND '2022-10-31') AS H
WHERE C.CAR_ID = H.CAR_ID AND C.CAR_TYPE = '세단'
ORDER BY H.CAR_ID DESC;