SELECT COUNT(*) AS COUNT
FROM ECOLI_DATA
WHERE INSTR(SUBSTR(REVERSE(CONV(GENOTYPE, 10, 2)), 2), 1) != 1 -- 2번 형질 보유하지 않음
      AND (INSTR(SUBSTR(REVERSE(CONV(GENOTYPE, 10, 2)), 1), 1) = 1 -- 1번 형질 보유
      OR INSTR(SUBSTR(REVERSE(CONV(GENOTYPE, 10, 2)), 3), 1) = 1)  -- 3번 형질 보유
